name: arabic_speaker_child
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  moyasar_payment: ^0.1.5
  #unicode_moyasar: ^1.0.3 
  text_to_speech: ^0.2.3
  device_info_plus: ^8.1.0
  shared_preferences: ^2.0.15
  drag_select_grid_view: ^0.5.1
  flutter_tts: ^3.5.3
  share_plus: ^7.0.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  http: ^0.13.4
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_storage: ^11.0.16
  path_provider: ^2.0.11
  cached_network_image: ^3.2.1
  flutter_draggable_gridview: ^0.0.6
  flutter_colorpicker: ^1.0.3
  volume_controller: ^2.0.3
  just_audio: ^0.9.28
  flutter_audio_recorder2: ^0.0.2
  keyboard_dismisser: ^3.0.0
  provider: ^6.0.3
  dio: ^4.0.6
  firebase_database: ^10.0.16
  audioplayers: ^1.0.1
  just_audio_cache: ^0.1.1
  flutter_cache_manager: ^3.3.0
  rename: ^2.0.1
  animated_search_bar: ^2.3.0
  animated_notch_bottom_bar: ^0.0.6
  get: ^4.6.5
  concentric_transition: ^1.0.3
  url_launcher: ^6.1.7
  flutter_snake_navigationbar: ^0.6.1
  lottie: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/uiImages/logobg.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/IconLib/actions/
    - assets/IconLib/Animall/
    - assets/IconLib/body/
    - assets/IconLib/careers/
    - assets/IconLib/clothes/
    - assets/IconLib/colors-m/
    - assets/IconLib/family/
    - assets/IconLib/food/
    - assets/HowToUse/
    - assets/IconLib/Places/
    - assets/IconLib/transportation/
    - assets/IconLib/worship/
    - assets/IconLib/Home/
    - assets/IconLib/directione/
    - assets/IconLib/School/
    - assets/IconLib/Shapes/
    - assets/images/
    - assets/uiImages/


  fonts:
    - family: Changa
      fonts:
        - asset: fonts/Changa-VariableFont_wght.ttf
    - family: Almarai
      fonts:
        - asset: fonts/Almarai-Regular.ttf
        - asset: fonts/Almarai-Bold.ttf
        - asset: fonts/Almarai-ExtraBold.ttf

